name: "Container Image Artifact Upload"
description: "Uploads container image as an artifact"
inputs:
  image:
    description: Container image to upload
    required: true
  retention_days:
    description: Retention days for the image artifact
    required: false
    default: "0"
  container_engine:
    description: Container engine to leverage for packaging an image
    required: false
    default: "docker"
outputs:
  artifact_name:
    description: Name of artifact created in the process
runs:
  using: "node20"
  main: "dist/main.js"
