name: E2E Test - Podman
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
jobs:
  build-test-image:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.upload_artifact.outputs.artifact_name }}
    steps:
      - name: Install podman
        run: |
          sudo apt-get update && sudo apt-get install podman

      - name: Build test image
        run: |
          podman build -t test_image:${{ github.run_id }} -<<EOF
            FROM busybox
            RUN touch abc.txt
          EOF

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload image artifact
        id: upload_artifact
        uses: ./
        with:
          image: "test_image:${{ github.run_id }}"
          retention_days: "1"
          container_engine: "podman"
    
  run-e2e-test:
    needs: build-test-image
    runs-on: ubuntu-latest
    steps:
      - name: Install podman
        uses: gacts/install-podman@v1

      - name: Test artifact exists
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-test-image.outputs.artifact_name }}

      - name: Test artifact is loadable
        run: |
          podman load -i ${{ steps.download-artifact.outputs.download-path }}/test_image_${{ github.run_id }}
